### ISSUE TITLE
Cross env

### ISSUE THREAD

**Issue by larsvankleef** [kaliberjs/build#119]
I think there is no ambition to get this build stack running on windows. But i found this package that looks pretty use full.

`https://www.npmjs.com/package/cross-env`

**Comment by EECOLOR** [comment]
Great find! Might indeed come in useful one day.

You are right to say that we currently don't have an ambition to run on windows. There might be other locations where we use a forward `/` in paths instead of the windows `\`. So I will close the issue and we can re-open it in the future if we decide we do want to support windows.

Thank you very much, this type of input is very much appreciated!

**Comment by BillyBlaze** [comment]
As a windows user I was unable to run it, therefor I have looked a bit into this issue and it seems the path separators are already resolved through the [Path API](https://nodejs.org/api/path.html), so that seems on first sight not a problem.

I was able to get this working on a Windows machine by changing the environment variables to cli arguments and by using a simple [argv](https://nodejs.org/docs/latest/api/process.html#process_process_argv) parser like [minimist](https://www.npmjs.com/package/minimist).

**Comment by EECOLOR** [comment]
@BillyBlaze You can use environment variables in windows: https://superuser.com/questions/1049430/how-do-you-set-environment-variables-for-a-single-command-on-windows
