### ISSUE TITLE
Restructure yarn workspaces

### ISSUE THREAD

**Issue by klaaz0r** [kaliberjs/build#132]
Instead of having `docs` and `example` as a workspace maybe we can restructure the build tool more like this: 

```
packages/root 
  - webpack
  - scaffold 
  ...
```
on future features this would separate functionality in a cleaner way for example having `@kaliber/components`

**Comment by EECOLOR** [comment]
I'm not sure I follow. The `kaliberjs/build` repository produces a single library which is released as `@kaliber/build` (same with `kaliberjs/config`).

Currently the repository is structured as follows:

- `example` - An example showcasing some of the features of the library
- `docs` - The documentation of the library
- `library` - The library itself

The workspaces are there because it allows us to run `docs` and `example` on the current version of the library while being separate javascript projects with their own dependencies.

The `library` contains the actual code for the library which includes the `kaliber-build`, `kaliber-watch`, `kaliber-serve`, `kaliber-lint` and `kaliber-scaffold` commands.

If we get `@kaliber/components` in the future I am quite sure it would live in the `kaliberjs/components` repository.

Having said that, I'm very curious what you have in mind. Can you sketch out what the organisation of the repo (the directories) looks like in your mind?

**Comment by EECOLOR** [comment]
Please re-open if you have more input
