### ISSUE TITLE
Allow named export of universal component

### ISSUE THREAD

**Issue by JoostKiens** [kaliberjs/build#178]
It seems universal components only work when imported through a default export.

If I use a named export I get the following message in my terminal

```
    WARNING in ./nouveau/App.js?universal-client 7:30-39
    "export 'default' (imported as 'Component') was not found in './App.js'
```

**Comment by JoostKiens** [comment]
BTW the application assumes a default export of template files (foo.bar.js) as well, is this something we would like to change?

**Comment by EECOLOR** [comment]
This is not something we plan on supporting. Exporting a non-default in these cases requires us to add another convention: the name of the exported component. Since `default` is the convention in the Javascript ecosystem (it even made it into the language in the form of the `default` keyword) I think it would be best to use that.

I'm open for arguments to convince me moving away from this convention.

**Comment by JoostKiens** [comment]
Clear, seems fine to me, what would be the best way to suppress linting warnings? 

- Perhaps make a linting rule for an exception based on file name convention for template files?
- Disable the warning with a comment on universal

**Comment by EECOLOR** [comment]
@JoostKiens while this is an issue for a non-released branch. We are no longer enforcing those linting rules on files that end with `App.js` or match the following regular expression: `/.+\.[^.]+\.js/` (`index.html.js`).
