### ISSUE TITLE
Config env is required even if no config is necessary

### ISSUE THREAD

**Issue by JoostKiens** [kaliberjs/build#181]
In the current scaffolding there's no CONFIG_ENV for dev, which means `start` doesn't work. Seems it would make more sense to make config optional.

**Comment by EECOLOR** [comment]
Hmm, I think I don't get it. It seems the scaffold command provides a `CONFIG_ENV=dev` for `watch` and `serve.dev` (called by `start`) and also provides a `config/dev.js` file.

What am I missing?

**Comment by EECOLOR** [comment]
Also, it has been like this since version 60: https://github.com/kaliberjs/build/commit/bb595080eabac756a5146ee1b2c60bb50e91c163

I can't remember the exact details (it's been quite a while), but I think we made it a requirement because one of the servers was configured incorrectly causing unexpected behavior.

**Comment by JoostKiens** [comment]
My bad, I meant prd. not dev. Closing this issue
