### ISSUE TITLE
Configurable basic auth for the kaliber-serve

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#43]
Test- and acceptance-environments should for example be password-protected.

**Comment by klaasman** [comment]
@EECOLOR perhaps we can make this configurable via the config dir, something like:
```js
// config/acc.js

module.exports = {
  '@kaliber/build': {
    basicAuthentication: {
      enabled: true,
      username: "xxx",
      password: "xxx"
    }
  }
}

```

**Comment by EECOLOR** [comment]
Since we have `@kaliber/config` by default I think we should do the following:

```
const { serve } = require('@kaliber/config')
...
app.use(serve)
```
The problem with this is that people could configure it with anything, the upside is that people could configure it with everything.

Internally we should make some conventions for commercial projects, but it would allow us to hack on stuff outside of commercial projects.

Your example would then be:

```
const basicAuth = require('express-basic-auth')

module.exports = {
  serve: basicAuth({
    users: { admin: 'supersecret' }
  })
}
```

Since `use` accepts about anything (routes, apps, arrays, ...) you could configure anything you want.
