### ISSUE TITLE
CSS url properties fail if they contain an id

### ISSUE THREAD

**Issue by JoostKiens** [kaliberjs/build#53]
CSS properties which contain `url()`, can contain references to IDs, however they trigger an error: 'can't find resource'.

These should all be valid:
```
mask: url(masks.svg);
mask: url(#star);
mask: url(masks.svg#star);   
```

**Comment by EECOLOR** [comment]
It will probably be tricky to support `masks.svg`.

The `post-css-url-replace` plugin in `lib/` is the one that searches for `url(xxx)` and since it's a post-css plugin it theoretically knows the context of the `url(xxx)`.

In our css plugin we use the url replace plugin to resolve stuff through webpack, this allows for things like inlining images. If this regex matches, it will try to resolve through webpack: `/^data:|^(https?:)?\/\//`

We could extend this to add the `#` char. But it feels like the `mask` property is one of those things where the url does not point to a file ever. I however am not familiar with it, so I would need to read up on it to better understand it.

**Comment by EECOLOR** [comment]
Ok, well that was fun in testing if I did it correctly: https://bugs.chromium.org/p/chromium/issues/detail?id=109212

The `masks.svg#star` version is a bit broken...
