### ISSUE TITLE
@import is not working as expected in component.css

### ISSUE THREAD

**Issue by larsvankleef** [kaliberjs/build#59]
I got a error when importing a node module into component.css. (This is not really a normal use case)

```ssh
Module build failed: CssSyntaxError: postcss-import: node_modules/flickity/js/index.js:12:1:
```
This is a problem where the resolver is not getting the styles from the package.json of the module.

**Comment by EECOLOR** [comment]
It's this key in it's `package.json`: `"style": "css/flickity.css"`

We'll have to figure out if it's even possible to have a different resolver setting (see https://webpack.js.org/configuration/resolve/#resolve-mainfields) when in the context of a css file.

This however gives us another problem: `postcss-import` simply inlines the imported stylesheet. Since we have `css-modules`, the class names of the imported css would be hashed rendering them unusable.

_Extra info_

`postcss-import` states:
> When importing a module, it will look for index.css or file referenced in package.json in the style or main fields. You can also provide manually multiples paths where to look at.

We however override the `resolve` function to make sure the same resolution rules are used for css as for javacript.

The whole subject is a bit of a slippery slope: https://github.com/css-modules/css-modules/pull/65

**Comment by EECOLOR** [comment]
Oh, for now I suggest we simply use the following workaround: import from your (javascript) template:

```
import 'flickity/css/flickity.css'
```

**Comment by EECOLOR** [comment]
I think that, for now, we should not do anything until the css-module community has a solution like this:

```
:global {
   import('x')
}
```

**Comment by EECOLOR** [comment]
https://github.com/a-x-/postcss-global-nested/issues/1

We can revisit this once the postcss community has a solution for this.
