### ISSUE TITLE
Styling is one tick behind

### ISSUE THREAD

**Issue by dennispassway** [kaliberjs/build#61]
On saving, the css is not updating while the hash in the head is updated. After saving again, it updates correctly so it seems like it's one tick behind.

**Comment by EECOLOR** [comment]
Ahh, yes. The problem is that hot reloading was created for Javascript and thus is only attached to the web compiler. The web compiler runs inside the node compiler and will give a reload signal as soon as the inner compilation is finished.

We rigged the hot reloader to also refresh the css. The issue here is that css is emitted by the 'outer' (node) compiler and that the reload signal has already been sent out, before the new file exists.

We could simply send the reload signal once the outer compiler is ready, but that would add a delay to javascript hot reloading and will have some other complications (which I can not remember).

I have to think about the best solution here. Maybe we should remove the css reloading from the hot module replacement client and introduce a specialized css version for the outer compiler. That would have the benefit of having css reloading for non-universal sites.

Maybe @klaasman has even better ideas
