### ISSUE TITLE
Clean urls

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#67]
Is it bad practice to redirect all requests with trailing slashes to non-trailing slashes?

If not, I'd like this feature :-)

**Comment by EECOLOR** [comment]
Yes, haha, it is. Maybe the world will change it's opinion, but it's not there yet. If you start the example and go to `http://localhost:8000/test` it will redirect to `/test/`.

The difference is that `/test` points to a directory which contains an `index.html`. We could theoretically create a `/test` file (instead of the directory) that contains the same stuff as `index.html`. There is no theoretical reason a file named `/test` and a directory `/test/` could not exist next to each other apart from most file systems not supporting this.

This is what google has to say about it: https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html

Main thing from that: "use one (with or without and redirect the other) and keep it consistent in links, sitemaps, etc."

Since the slash at the root is mandatory, we probably should keep the slash at the end. Another reason in favor of this the way we set up the server (mainly `express.static`):
- The use of directories in combination with `index.html`.
- Automatic content type based on extension.

My personal favorite would be without slash, but that would require us to rewrite (or probably write) a lot of stuff that is 'free' now.

So my advise: 'redirect all stuff without extension and without a slash to the thing with a slash'

**Comment by EECOLOR** [comment]
@klaasman Can we close this issue?

**Comment by klaasman** [comment]
Yes, I'm not sure `@kaliber/build` should handle this - I guess it's better to have consistent canonical urls in the application.

**Comment by EECOLOR** [comment]
When we create libraries that help with routing we can make it consistent there
