### ISSUE TITLE
How should we deal with polyfills?

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#91]

**Comment by EECOLOR** [comment]
I think we might want to rename this issue.

In any case, we need a solid way to work with polyfills. I did some clicking on the internet and found this one: https://github.com/cle1994/express-polyfill-service

`serve.js`
```js
const polyfill = require('express-polyfill-service')

...
app.use('/polyfill.js', polyfill({ minify: true, features: { default: {} } }))
...
```

And then in the `html` (as the first script):
```html
<script defer type="application/javascript" src="/polyfill.js"></script>
```

This library is a very lightweight wrapper around [Polyfill service](https://polyfill.io/v2/docs/), so lightweight that we might actually choose to implement the code itself in order to add the appropriate caching headers (if that's not provided by the other plugins we have installed). See [Github/polyfill-service#library](https://github.com/Financial-Times/polyfill-service#library) for details.

It took me a while to realize what this service does, but now that I understand it, it's quite good. It reads the user agent string and uses that to determine which polyfills are required. The `default` set gets updated automatically. In the case where we use an express service and host it ourselves it would only update on a new release. If we were to use their CDN deployed version it would be always up-to-date:

```html
<script defer src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
```
They take it pretty seriously:
- [Browsers and features](https://polyfill.io/v2/docs/features/)
- [Statistics](https://polyfill.io/v2/docs/usage)

All in all I think this is what we want to use instead of manually adding polyfills.

As for the choice between their hosted CDN or intergrated in our serve. I think we should check the effect and speed of their CDN. If it's fast enough I would go for that.

**Comment by EECOLOR** [comment]
We might need something like this: https://github.com/Financial-Times/babel-polyfill-silencer

**Comment by EECOLOR** [comment]
Or simply the babel option: `{ polyfill: false }`

**Comment by EECOLOR** [comment]
Extra tips and tricks: http://origami.ft.com/docs/developer-guide/modules/using-the-polyfill-service/?mhq5j=e7

**Comment by EECOLOR** [comment]
Some extra info: https://github.com/Financial-Times/polyfill-service/issues/1099

**Comment by EECOLOR** [comment]
My current opinion is to go with the hosted polyfill service. Now that we have a scaffold thingy, we can add a sensible default there.

**Comment by klaasman** [comment]
I'm not sure about a hosted service, it will be an extra dependency during runtime which may cause downtime for several of our applications. Bundling this service in our application would have my preference.

**Comment by klaasman** [comment]
Let's just give it a try and see where it ends :-)
